### ISSUE TITLE
Questions about LLaVA checkpoints

### ISSUE THREAD

**Issue by lsnls** [aldraus/quilt-llava#11]
Hello! Thank you for your valuable work! 

As shown in the figure, your paper mentioned `LLaVA checkpoint,7B language Model`, and I would like to ask you a few questions:

1. Since LLaVA open-source many weights, is the weight you using `LLaVA-1.5 7b full_ft-1e`?

2. Do you use full tune or LoRA fine-tune for the 2 stages of training?

3. How do you load the initial weights of `Llava`?  Do you pass the path of the LLaVA weights to both the `model_name_or_path` and the `vision_tower` in `pretrain.sh`?

I'm looking forward to your reply! Thank you very much!

![image](https://github.com/aldraus/quilt-llava/assets/154673615/e0f16a59-e1c7-4346-99bf-97ecfb891df2)

**Comment by wisdomikezogwo** [comment]
Hi,

To start we open source our best-performing open-question model: QUILTNET ViT-B-32 Vision Encoder, 7B Language Model (i.e. lmsys/vicuna-7b-v1.5 + QuiltNet B-32).

To answer your questions:
1. We use liuhaotian/llava-v1.5-7b was as discussed in the paper and as can be found in `scripts/v1_5/finetune_task.sh`
2. No, we do not use LoRA
3. I'll assume you are asking about the 1st pretrain stage on liuhaotian/llava-v1.5-7b. Yes, we use: `--model_name_or_path liuhaotian/llava-v1.5-7b \. --vision_tower openai/clip-vit-large-patch14-336 \`

**Comment by lsnls** [comment]
I see, thank you very much for your reply!!
