### ISSUE TITLE
Multichoice questions issue

### ISSUE THREAD

**Issue by Lewislou** [aldraus/quilt-llava#18]
Hi,

I have tried to ask the quilt-llava model to give a assumption on whether a WSL is tumor or normal. But it will only give a random guess. Can this model do any WSI classification task?

For example:
Q1: Based on the image from the Breast. What is the most likely diagnosis?. Give me your choice:  B. Normal breast tissue, A. Breast carcinoma;.
A1: B. Normal breast tissue

Q2: Based on the image from the Breast. What is the most likely diagnosis?. Give me your choice:  A. Breast carcinoma, B. Normal breast tissue,;.
A2: A. Breast carcinoma

The two questions are the same, but it will output two different answers. I have tried many other images, the results are the same.

**Comment by aldraus** [comment]
Interesting observation. We hypothesize it could be due to the phenomenon mentioned in https://arxiv.org/pdf/2405.18415

**Comment by aldraus** [comment]
Also, we do not have such samples in our instruction tuning dataset. If this is your aim, please further fine-tune the model with this kind of Q/A structure. It will surely help.

**Comment by Lewislou** [comment]
> Also, we do not have such samples in our instruction tuning dataset. If this is your aim, please further fine-tune the model with this kind of Q/A structure. It will surely help.

Hi, thanks for your suggestion. I tried to finetune the quilt-Llava model using my own dataset using Lora. So I changed the --pretrain_mm_mlp_adapter in finetune__lora.sh as the mm_projector.bin that was downloaded from 'https://huggingface.co/wisdomik/Quilt-Llava-v1.5-7b/tree/main/'. But I got the error indicated that the dimensions of model and chekpoint of the mm_projector are not match.

![image](https://github.com/aldraus/quilt-llava/assets/23080469/6e48f153-7c27-40d0-a9f0-ab8a9f8a614b)

Did I do anything wrong?
