### ISSUE TITLE
Some Weights not used when initializing LlavaLlamaForCausalLM

### ISSUE THREAD

**Issue by bryanwong17** [aldraus/quilt-llava#23]
Hi, I received a warning when trying to load the `wisdomik/Quilt-Llava-v1.5-7b` model. How can I resolve this issue? Is this warning critical, or can it be safely ignored?

![image](https://github.com/user-attachments/assets/2fd47c7f-6947-4cab-b660-85d1ea5cb31e)

**Comment by casperliuliuliu** [comment]
same here.
The answer seems to be correct, but still concerning.

**Comment by wisdomikezogwo** [comment]
We mention this behavior in the [README](https://github.com/aldraus/quilt-llava?tab=readme-ov-file#cli-inference) also see: https://github.com/haotian-liu/LLaVA/issues/672 . Most important note: it doesn't affect model loading or performance.
