### ISSUE TITLE
inquiring about image captioning？

### ISSUE THREAD

**Issue by xuanxu92** [aldraus/quilt-llava#4]
Hi, i really appreciate this excellent work. is it possible that these could be used for histopathology image captioning?
thanks!

**Comment by evgenfm** [comment]
Thank you! It's definitely worth trying. However, you may need a different set of instructions or a tuning dataset for better performance.

**Comment by aldraus** [comment]
Thank you! It's definitely worth trying. However, you may need a different set of instructions or a tuning dataset for better performance.
