### ISSUE TITLE
PMC-VQA-Subset

### ISSUE THREAD

**Issue by lsnls** [aldraus/quilt-llava#8]
Hello, thank you for your outstanding work!

You used a `PMC-VQA-Subset` with 2469 VQA pairs, could you please open source the subset?

Thank you very much!

**Comment by wisdomikezogwo** [comment]
Hi,

Please see the PMCVQA section in [docs/Evaluation.md](https://github.com/aldraus/quilt-llava/blob/a7a9a4c3ddccea6011e5ba34e8666514b855b93a/docs/Evaluation.md) to see how to download and pre-process this subset.

Thanks.

**Comment by lsnls** [comment]
Thank you very much for opening source these datasets!

**Comment by lsnls** [comment]
Hello!

After I clicked on the link of `pmcvqa_pathology_subset.csv` in the `Evaluation.md`, the webpage showed `Repository not found`. 

Hope to get your help. Thank you so much!

**Comment by lsnls** [comment]
Hello!

I found `pmcvqa_pathology_subset.csv` under your Huggingface repository `wisdomik/QuiltVQA_RED` and I guess that's the file I want to download.
