### ISSUE TITLE
model_vqa_science.py not found

### ISSUE THREAD

**Issue by lsnls** [aldraus/quilt-llava#9]
Hi! Thank you for your very helpful work!

When I run the `pmc_vqa.sh`, `llava.eval.model_vqa_science.py` is missing.

Looking forward to your reply! Thank you!

**Comment by wisdomikezogwo** [comment]
Thanks for pointing that out, It's been added in. I apologize for the issue, we were trying to make the codebase as lean as possible and missed that eval code. Let us know if you run into any other issues.

**Comment by lsnls** [comment]
Hi! Thank you for your reply.

When I run the `quilt_red_vqa.sh`, `quiltvqa_red_test_wo_ans.jsonl` is missing. I download the `red_circle.zip`, but there isn't the missing file.

Looking forward to your reply! Thank you!
